/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A synth driven by JSON commands. */
export declare class Synth {
  /** Build a synth from a spec JSON string. */
  constructor(specJson: string)
  /** Apply a command envelope (`{"cmd":"...", ...}`) and return the response JSON. */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
